name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

   - name: Install dependencies for UI
     working-directory: ./ui
     run: npm install

   - name: Run Jest tests for UI
     working-directory: ./ui
     run: npm test

    - name: Install dependencies for API
      working-directory: ./api
      run: npm install

    - name: Run Jest tests for API  
      working-directory: ./api
      run: npm test

    - name: Install dependencies for E2E
      working-directory: ./e2e
      run: npm install  

      - name: Run Playwright tests for E2E
        working-directory: ./e2e
        run: npm test 